### ISSUE TITLE
Plots are not displayed/executed

### ISSUE THREAD

**Issue by imerelli** [jupyterlab/jupyter-collaboration#351]
Hi,

I'm trying to use jupyverse to support server-side execution as reported in https://github.com/jupyterlab/jupyter-collaboration/pull/279 and for motivations similar to https://github.com/jupyterlab/jupyterlab/issues/2833.

Here my configuration, a very simple conda env (installed with "mamba create --name jupyter python=3.10") and then these packages installed using pip install --pre (apart form jupyterlab for which I'm using version 4.2.5 as suggested in a previous post)

```
pip list | grep jupy
fps_jupyterlab                    0.6.0
jupyter                           1.1.1
jupyter_client                    8.6.2
jupyter-collaboration             3.0.0b3
jupyter-collaboration-ui          1.0.0b3
jupyter-console                   6.6.3
jupyter_core                      5.7.2
jupyter-docprovider               1.0.0b3
jupyter-events                    0.10.0
jupyter-lsp                       2.2.5
jupyter_server                    2.14.2
jupyter_server_fileid             0.9.3
jupyter_server_terminals          0.5.3
jupyter-server-ydoc               1.0.0b3
jupyter-ydoc                      3.0.0a6
jupyterlab                        4.2.5
jupyterlab_pygments               0.3.0
jupyterlab_server                 2.27.3
jupyterlab_widgets                3.0.13
jupyverse                         0.6.0
jupyverse_api                     0.6.0
lckr_jupyterlab_variableinspector 3.2.1
```

Then I started jupyverse (on a remote server and I'm connecting to it from my laptop over internet) using:

jupyverse --host 0.0.0.0 --port 80 --set kernels.require_yjs=true --set jupyterlab.server_side_execution=true

But plots are not displayed (not even executed, I think, because even writing them the a file fails). See image below 

![jupyverse](https://github.com/user-attachments/assets/5f80614d-e6d2-4624-ac36-a63e2fd38f36)

Using the normal jupyter lab everything is fine. And also using jupyverse without --set kernels.require_yjs=true --set jupyterlab.server_side_execution=true

Am I doing something wrong?

**Comment by davidbrochart** [comment]
Thanks for reporting the issue @imerelli, this should be fixed in Jupyverse v0.6.2.

**Comment by imerelli** [comment]
Hi, I just tried with jupyverse 0.6.2, but I have the same error as before.
Am I missing something?

```
pip list | grep jupy
fps_jupyterlab                    0.6.0
jupyter                           1.1.1
jupyter_client                    8.6.2
jupyter-collaboration             3.0.0b3
jupyter-collaboration-ui          1.0.0b3
jupyter-console                   6.6.3
jupyter_core                      5.7.2
jupyter-docprovider               1.0.0b3
jupyter-events                    0.10.0
jupyter-lsp                       2.2.5
jupyter_server                    2.14.2
jupyter_server_fileid             0.9.3
jupyter_server_terminals          0.5.3
jupyter-server-ydoc               1.0.0b3
jupyter-ydoc                      3.0.0a6
jupyterlab                        4.2.5
jupyterlab_pygments               0.3.0
jupyterlab_server                 2.27.3
jupyterlab_widgets                3.0.13
jupyverse                         0.6.2
jupyverse_api                     0.6.2
lckr_jupyterlab_variableinspector 3.2.1
```

**Comment by davidbrochart** [comment]
Can you try with regular releases of `jupyter-ydoc` and `jupyter-collaboration` (not pre-releases)?

**Comment by imerelli** [comment]
Still the same problem with this configuration, 
that should have the regular releases of jupyter-ydoc and jupyter-collaboration

```
(jupyter) [root@tiget-7 ~]# pip list | grep jupy
WARNING: Ignoring invalid distribution -upyterlab-server (/opt/miniforge3/lib/python3.10/site-packages)
fps_jupyterlab                    0.6.0
jupyter                           1.1.1
jupyter_client                    8.6.2
jupyter_collaboration             2.1.2
jupyter-collaboration-ui          1.0.0b3
jupyter-console                   6.6.3
jupyter_core                      5.7.2
jupyter-docprovider               1.0.0b3
jupyter-events                    0.10.0
jupyter-lsp                       2.2.5
jupyter_server                    2.14.2
jupyter_server_fileid             0.9.3
jupyter_server_terminals          0.5.3
jupyter-server-ydoc               1.0.0b3
jupyter-ydoc                      2.1.1
jupyterlab                        4.2.5
jupyterlab_pygments               0.3.0
jupyterlab_server                 2.27.3
jupyterlab_widgets                3.0.13
jupyverse                         0.6.2
jupyverse_api                     0.6.2
lckr_jupyterlab_variableinspector 3.2.1
```

**Comment by imerelli** [comment]
Hi, I think the problem persists, or maybe I haven’t found the right combination of package versions. Could you help me solve this issue?

**Comment by davidbrochart** [comment]
> Can you try with regular releases of `jupyter-ydoc` and `jupyter-collaboration` (not pre-releases)?

You are still using a pre-release of jupyter-collaboration. Could you start from a fresh environment?
```bash
pip install "jupyverse[jupyterlab, auth]"
jupyverse --set kernels.require_yjs=true --set jupyterlab.server_side_execution=true
```

**Comment by imerelli** [comment]
Ok, it worked. Clearly I also installed jupyter-collaboration after this.

```
pip install --upgrade --pre jupyter-collaboration
```

Thanks
